comunidaddo/events/urls.py
from django.urls import path

from . import views


app_name = "events"

urlpatterns = (
    # urls for Event
    path('',
         views.EventListView.as_view(),
         name='event_list'),
    path('create/',
         views.EventCreateView.as_view(),
         name='event_create'),
    path('<slug:slug>/',
         views.EventDetailView.as_view(),
         name='event_detail'),
    path('update/<slug:slug>/',
         views.EventUpdateView.as_view(),
         name='event_update'),
)

comunidaddo/users/urls.py
from django.urls import path

from comunidaddo.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path("",
         TemplateView.as_view(
             template_name="pages/home.html"),
         name="home"),
    path(
        "about/",
        TemplateView.as_view(
            template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("comunidaddo.users.urls", namespace="users"),
    ),
    path(
        "events/",
        include("comunidaddo.events.urls", namespace="events"),
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

comunidaddo/events/models.py
from django.urls import reverse
from django.conf import settings
from django.db import models
from django_extensions.db import fields as extension_fields


class Event(models.Model):
    slug = extension_fields.AutoSlugField(
        populate_from='title', blank=True)
    created = models.DateTimeField(
        auto_now_add=True, editable=False)
    last_updated = models.DateTimeField(
        auto_now=True, editable=False)
    title = models.CharField(max_length=250)
    description = models.TextField()
    url = models.URLField(null=True, blank=True)
    image = models.ImageField(
        upload_to="events", null=True, blank=True)
    start_date = models.DateField()
    end_date = models.DateField()
    publish = models.BooleanField(default=True)
    publish_date = models.DateTimeField(auto_now_add=True)
    address = models.CharField(max_length=250)
    country = models.CharField(max_length=150)
    city = models.CharField(max_length=150)

    # Relationship Fields
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='events',
        on_delete=models.CASCADE)
    region = models.ForeignKey(
        "region", on_delete=models.CASCADE)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Event: {self.slug}'

    def get_absolute_url(self):
        return f"/events/{self.slug}"

    def get_update_url(self):
        return f"/events/update/{self.slug}"


class Region(models.Model):
    name = models.CharField(max_length=255)
    slug = extension_fields.AutoSlugField(populate_from='name', blank=True)
    created = models.DateTimeField(auto_now_add=True, editable=False)
    last_updated = models.DateTimeField(auto_now=True, editable=False)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse('events_region_detail', args=(self.slug,))

    def get_update_url(self):
        return reverse('events_region_update', args=(self.slug,))

comunidaddo/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

comunidaddo/events/forms.py
from django import forms
from .models import Event, Region


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = [
            'title', 'description',
            'url', 'image', 'start_date',
            'end_date', 'address', 'country',
            'city', 'user', 'region']
        widgets = {
            'user': forms.HiddenInput()}


class RegionForm(forms.ModelForm):
    class Meta:
        model = Region
        fields = ['name']

comunidaddo/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):

    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

comunidaddo/events/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, ListView, UpdateView, CreateView
from .models import Event
from .forms import EventForm


class EventListView(ListView):
    model = Event


class EventCreateView(LoginRequiredMixin, CreateView):
    model = Event
    form_class = EventForm

    def get_initial(self):
        initial = super().get_initial()
        initial['user'] = self.request.user.pk
        return initial


class EventDetailView(DetailView):
    model = Event


class EventUpdateView(UpdateView):
    model = Event
    form_class = EventForm

comunidaddo/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserListView(LoginRequiredMixin, ListView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_list_view = UserListView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

comunidaddo/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

comunidaddo/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Comunidad DO{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}

    <!-- UIkit CSS -->
    <link rel="stylesheet" href="{% static 'css/main.min.css' %}" />
    <!-- This file stores project-specific CSS -->
    
    <link href="{% static 'css/project.min.css' %}" rel="stylesheet">
    
    {% endblock %}

  </head>

  <body>

    <div class="uk-container">
        <nav class="uk-navbar uk-margin" uk-navbar="mode: click">
            <div class="uk-navbar-left">
              <a class="uk-navbar-brand" href="{% url 'home' %}">Comunidad DO</a>
            </div>
            <div class="uk-navbar-right">
                <ul class="uk-navbar-nav">
                    <li class="uk-active"><a href="/events/">Events</a></li>
                    {% if request.user.is_authenticated %}
                      <li><a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a></li>
                      <li><a href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a></li>
                    {% else %}
                      <li class="nav-item"><a id="sign-up-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a></li>
                      <li class="nav-item"><a id="log-in-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        {% block content %}
        {% endblock content %}
    </div>

    <!-- Le javascript
    ================================================== -->
    {% block javascript %}
      <script src="https://code.jquery.com/jquery-3.3.1.slim.js" crossorigin="anonymous"></script>

      <!-- UIkit JS -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.9/js/uikit.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.9/js/uikit-icons.min.js"></script>

      <!-- place project specific Javascript in this file -->
      <script src="{% static 'js/project.min.js' %}"></script>

    {% endblock javascript %}
  </body>
</html>

comunidaddo/templates/events/base.html
<html><head></head><body>{% block content %}Replace this.{% endblock %}</body>

comunidaddo/templates/events/event_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'events:event_list' %}">Event Listing</a></p>
<table class="table">
<tr><td>title</td><td>{{ object.title }}</td></tr>
<tr><td>description</td><td>{{ object.description }}</td></tr>
<tr><td>url</td><td>{{ object.url }}</td></tr>
<tr><td>image</td><td>{{ object.image }}</td></tr>
<tr><td>start_date</td><td>{{ object.start_date }}</td></tr>
<tr><td>end_date</td><td>{{ object.end_date }}</td></tr>
<tr><td>address</td><td>{{ object.address }}</td></tr>
<tr><td>country</td><td>{{ object.country }}</td></tr>
<tr><td>city</td><td>{{ object.city }}</td></tr>
</table>
<a class="btn btn-primary" href="{{object.get_update_url}}">Edit Event</a>

{% endblock %}

comunidaddo/templates/events/event_form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'events:event_list' %}">Event Listing</a></p>
<form method="post">
{% csrf_token %}
{{form|crispy}}
<button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}

comunidaddo/templates/events/event_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'events:event_list' %}">Event Listing</a></p>
<table class="table">
<tr>
<td>ID</td><td>Link</td>
    <td>slug</td>
    <td>title</td>
    <td>description</td>
    <td>url</td>
    <td>image</td>
    <td>start_date</td>
    <td>end_date</td>
    <td>address</td>
    <td>country</td>
    <td>city</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{object.pk}}</td>
    <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
    <td>{{ object.slug }}</td>
    <td>{{ object.title }}</td>
    <td>{{ object.description }}</td>
    <td>{{ object.url }}</td>
    <td>{{ object.image }}</td>
    <td>{{ object.start_date }}</td>
    <td>{{ object.end_date }}</td>
    <td>{{ object.address }}</td>
    <td>{{ object.country }}</td>
    <td>{{ object.city }}</td>
</tr>
{% endfor %}
</table><a class="btn btn-primary" href="{% url 'events:event_create' %}">Create new Event</a>
{% endblock %}

comunidaddo/templates/events/region_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'events_region_list' %}">Region Listing</a></p>
<table class="table">
<tr><td>name</td><td>{{ object.name }}</td></tr>
<tr><td>slug</td><td>{{ object.slug }}</td></tr>
<tr><td>created</td><td>{{ object.created }}</td></tr>
<tr><td>last_updated</td><td>{{ object.last_updated }}</td></tr>
</table>
<a class="btn btn-primary" href="{{object.get_update_url}}">Edit Region</a>

{% endblock %}

comunidaddo/templates/events/region_form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'events_region_list' %}">Region Listing</a></p>
<form method="post">
{% csrf_token %}
{{form|crispy}}
<button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}

comunidaddo/templates/events/region_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'events_region_list' %}">Region Listing</a></p>
<table class="table">
<tr>
<td>ID</td><td>Link</td>
    <td>name</td>
    <td>slug</td>
    <td>created</td>
    <td>last_updated</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{object.pk}}</td>
    <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
    <td>{{ object.name }}</td>
    <td>{{ object.slug }}</td>
    <td>{{ object.created }}</td>
    <td>{{ object.last_updated }}</td>
</tr>
{% endfor %}
</table><a class="btn btn-primary" href="{% url 'events_region_create' %}">Create new Region</a>
{% endblock %}

comunidaddo/templates/pages/about.html
{% extends "base.html" %}

comunidaddo/templates/pages/home.html
{% extends "base.html" %}

{% block content %}
    <h3>Bienvenido a Comunidad DO!</h3>
{% endblock %}

comunidaddo/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

comunidaddo/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

comunidaddo/templates/users/user_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="container">
  <h2>Users</h2>

  <div class="list-group">
    {% for user in user_list %}
      <a href="{% url 'users:detail' user.username %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ user.username }}</h4>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}